# Generated by Django 5.2.1 on 2025-06-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
