# Generated by Django 5.2.1 on 2025-06-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_variation'),
        ('orders', '0002_remove_orderproduct_color_remove_orderproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Store.variation'),
        ),
    ]
